#include <stdio.h>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed the
// specified number (four million maximum), find the sum of the even-valued terms.
unsigned long int SumEvenFibonacci(unsigned long int number)
{
    unsigned long int term1 = 1, term2 = 2, sum = 0;

    while ( term1 < number )
    {
        unsigned long int prev = term1;

        if ( term1 % 2 == 0 )
        {
            sum += term1;
        }

        term1 = term2;
        term2 = prev + term2;
    }

    return sum;
}

void Test(int term) { printf("%s\n", term ? "true" : "false"); }

int main(void)
{
    Test( SumEvenFibonacci(0) == 0 );
    Test( SumEvenFibonacci(8) == 2 );
    Test( SumEvenFibonacci(89) == 44 );
    Test( SumEvenFibonacci(4000000) == 4613732 );
    return 0;
}
