// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed the
// specified number (four million maximum), find the sum of the even-valued terms.
function sumEvenFibonacci(number)
{
  var terms = [1, 1];
  var sum = 0;

  while ( terms[0] < number )
  {
    if ( terms[0] % 2 === 0 )
    {
      sum += terms[0];
    }
    
    terms = [terms[1], terms[0] + terms[1]];
  }

  return sum;
}

function isInteger(number)
{
  return !isNaN(number) &&
         parseInt(Number(number)) == number && 
         !isNaN(parseInt(number, 10));
}

function processInput()
{
  var value = valueElement.value;
  var resultElement = document.getElementById('result');

  if ( !isInteger(value) )
  {
    resultElement.style.color = "red";
    resultElement.innerHTML = "Error: Please enter an integer value.";
  }
  else if ( value < 0 || value > 4000000 )
  {
    resultElement.style.color = "red";
    resultElement.innerHTML = "Error: Please enter an integer between 0 and 4000000.";
  }
  else
  {
    resultElement.style.color = "black";
    resultElement.innerHTML = "Result: " + sumEvenFibonacci(value);
  }
}

var valueElement = document.getElementById('value');

addEventListener("keyup", function(event)
{
  if ( event.keyCode === 13 )
  {
    processInput();
  }
});